package com.iwy.wsdl.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DCQcreateTempMTAInput extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String sysDescr;
    
    private String macaddress;
    
    private String linesQty;
    
    public String getSysDescr()
    {
        return this.sysDescr;
    }
    
    public void setSysDescr(String value)
    {
        this.sysDescr = value;     
    }
    
    public String getMacaddress()
    {
        return this.macaddress;
    }
    
    public void setMacaddress(String value)
    {
        this.macaddress = value;     
    }
    
    public String getLinesQty()
    {
        return this.linesQty;
    }
    
    public void setLinesQty(String value)
    {
        this.linesQty = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("sysDescr"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.sysDescr = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.sysDescr = (String)obj;
                }
                else{
                    this.sysDescr = "";
                }
            }
            return true;
        }
        if (info.name.equals("macaddress"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.macaddress = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.macaddress = (String)obj;
                }
                else{
                    this.macaddress = "";
                }
            }
            return true;
        }
        if (info.name.equals("linesQty"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.linesQty = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.linesQty = (String)obj;
                }
                else{
                    this.linesQty = "";
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.sysDescr;
        }
        else if(propertyIndex==1)
        {
            return this.macaddress;
        }
        else if(propertyIndex==2)
        {
            return this.linesQty;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "sysDescr";
            info.namespace= "";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "macaddress";
            info.namespace= "";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "linesQty";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
