package com.iwy.wsdl.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DCQDocsisStatusObjOutput extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String idClienteCRM;
    
    private String nombre;
    
    private String username;
    
    private String macaddress;
    
    private String productName;
    
    private String manufacturer;
    
    private String hwv;
    
    private String swv;
    
    private String ip;
    
    private String cmts;
    
    private String upStream;
    
    private String downStream;
    
    private String ispCM;
    
    private String ispMTA;
    
    private String ispCPE;
    
    private String servicePackage;
    
    private String servicePackageID;
    
    private String dpiPackage;
    
    private String docsisVersion;
    
    private String cantPCs;
    
    private String disabled;
    
    private String cantMensajes;
    
    private String upTraffic;
    
    private String downTraffic;
    
    private String hub;
    
    private String nodo;
    
    private String CmStatus;
    
    private String uspl;
    
    private String dspl;
    
    private String dssnr;
    
    private String ussnr;
    
    private String pollingSource;
    
    private String pollingDate;
    
    private String pollingage;
    
    private String sysuptime;
    
    private String status;
    
    private DCQArrayOfLeasesObj cmLeases;
    
    private DCQArrayOfLeasesObj cpeLeases;
    
    private DCQArrayOfLeasesObj mtaLeases;
    
    private DCQArrayOfMensajesObj mensajes;
    
    private DCQArrayOfPoolingObj pooling;
    
    private DCQspDescriptionObj spDescription;
    
    private String mtaCMSName;
    
    private String mtaMacAddress;
    
    private String mtaHostname;
    
    private String mtaFQDN;
    
    private String mtaIPAddress;
    
    private String pktcMtaDevProvStateCode;
    
    private String pktcMtaDevProvStateString;
    
    private String epStatus;
    
    private String iCmNetworkUsage;
    
    private String iMtaNetworkUsage;
    
    private String iCpeNetworkUsage;
    
    private String cmActivationCode;
    
    private String cmFechaAlta;
    
    private String cmFechaActivacion;
    
    private String cmFechaModificacion;
    
    private String mtaActivationCode;
    
    private String mtaFechaAlta;
    
    private String mtaFechaActivacion;
    
    private String mtaFechaModificacion;
    
    private String serialNumber;
    
    public String getIdClienteCRM()
    {
        return this.idClienteCRM;
    }
    
    public void setIdClienteCRM(String value)
    {
        this.idClienteCRM = value;     
    }
    
    public String getNombre()
    {
        return this.nombre;
    }
    
    public void setNombre(String value)
    {
        this.nombre = value;     
    }
    
    public String getUsername()
    {
        return this.username;
    }
    
    public void setUsername(String value)
    {
        this.username = value;     
    }
    
    public String getMacaddress()
    {
        return this.macaddress;
    }
    
    public void setMacaddress(String value)
    {
        this.macaddress = value;     
    }
    
    public String getProductName()
    {
        return this.productName;
    }
    
    public void setProductName(String value)
    {
        this.productName = value;     
    }
    
    public String getManufacturer()
    {
        return this.manufacturer;
    }
    
    public void setManufacturer(String value)
    {
        this.manufacturer = value;     
    }
    
    public String getHwv()
    {
        return this.hwv;
    }
    
    public void setHwv(String value)
    {
        this.hwv = value;     
    }
    
    public String getSwv()
    {
        return this.swv;
    }
    
    public void setSwv(String value)
    {
        this.swv = value;     
    }
    
    public String getIp()
    {
        return this.ip;
    }
    
    public void setIp(String value)
    {
        this.ip = value;     
    }
    
    public String getCmts()
    {
        return this.cmts;
    }
    
    public void setCmts(String value)
    {
        this.cmts = value;     
    }
    
    public String getUpStream()
    {
        return this.upStream;
    }
    
    public void setUpStream(String value)
    {
        this.upStream = value;     
    }
    
    public String getDownStream()
    {
        return this.downStream;
    }
    
    public void setDownStream(String value)
    {
        this.downStream = value;     
    }
    
    public String getIspCM()
    {
        return this.ispCM;
    }
    
    public void setIspCM(String value)
    {
        this.ispCM = value;     
    }
    
    public String getIspMTA()
    {
        return this.ispMTA;
    }
    
    public void setIspMTA(String value)
    {
        this.ispMTA = value;     
    }
    
    public String getIspCPE()
    {
        return this.ispCPE;
    }
    
    public void setIspCPE(String value)
    {
        this.ispCPE = value;     
    }
    
    public String getServicePackage()
    {
        return this.servicePackage;
    }
    
    public void setServicePackage(String value)
    {
        this.servicePackage = value;     
    }
    
    public String getServicePackageID()
    {
        return this.servicePackageID;
    }
    
    public void setServicePackageID(String value)
    {
        this.servicePackageID = value;     
    }
    
    public String getDpiPackage()
    {
        return this.dpiPackage;
    }
    
    public void setDpiPackage(String value)
    {
        this.dpiPackage = value;     
    }
    
    public String getDocsisVersion()
    {
        return this.docsisVersion;
    }
    
    public void setDocsisVersion(String value)
    {
        this.docsisVersion = value;     
    }
    
    public String getCantPCs()
    {
        return this.cantPCs;
    }
    
    public void setCantPCs(String value)
    {
        this.cantPCs = value;     
    }
    
    public String getDisabled()
    {
        return this.disabled;
    }
    
    public void setDisabled(String value)
    {
        this.disabled = value;     
    }
    
    public String getCantMensajes()
    {
        return this.cantMensajes;
    }
    
    public void setCantMensajes(String value)
    {
        this.cantMensajes = value;     
    }
    
    public String getUpTraffic()
    {
        return this.upTraffic;
    }
    
    public void setUpTraffic(String value)
    {
        this.upTraffic = value;     
    }
    
    public String getDownTraffic()
    {
        return this.downTraffic;
    }
    
    public void setDownTraffic(String value)
    {
        this.downTraffic = value;     
    }
    
    public String getHub()
    {
        return this.hub;
    }
    
    public void setHub(String value)
    {
        this.hub = value;     
    }
    
    public String getNodo()
    {
        return this.nodo;
    }
    
    public void setNodo(String value)
    {
        this.nodo = value;     
    }
    
    public String getCmStatus()
    {
        return this.CmStatus;
    }
    
    public void setCmStatus(String value)
    {
        this.CmStatus = value;     
    }
    
    public String getUspl()
    {
        return this.uspl;
    }
    
    public void setUspl(String value)
    {
        this.uspl = value;     
    }
    
    public String getDspl()
    {
        return this.dspl;
    }
    
    public void setDspl(String value)
    {
        this.dspl = value;     
    }
    
    public String getDssnr()
    {
        return this.dssnr;
    }
    
    public void setDssnr(String value)
    {
        this.dssnr = value;     
    }
    
    public String getUssnr()
    {
        return this.ussnr;
    }
    
    public void setUssnr(String value)
    {
        this.ussnr = value;     
    }
    
    public String getPollingSource()
    {
        return this.pollingSource;
    }
    
    public void setPollingSource(String value)
    {
        this.pollingSource = value;     
    }
    
    public String getPollingDate()
    {
        return this.pollingDate;
    }
    
    public void setPollingDate(String value)
    {
        this.pollingDate = value;     
    }
    
    public String getPollingage()
    {
        return this.pollingage;
    }
    
    public void setPollingage(String value)
    {
        this.pollingage = value;     
    }
    
    public String getSysuptime()
    {
        return this.sysuptime;
    }
    
    public void setSysuptime(String value)
    {
        this.sysuptime = value;     
    }
    
    public String getStatus()
    {
        return this.status;
    }
    
    public void setStatus(String value)
    {
        this.status = value;     
    }
    
    public DCQArrayOfLeasesObj getCmLeases()
    {
        return this.cmLeases;
    }
    
    public void setCmLeases(DCQArrayOfLeasesObj value)
    {
        this.cmLeases = value;     
    }
    
    public DCQArrayOfLeasesObj getCpeLeases()
    {
        return this.cpeLeases;
    }
    
    public void setCpeLeases(DCQArrayOfLeasesObj value)
    {
        this.cpeLeases = value;     
    }
    
    public DCQArrayOfLeasesObj getMtaLeases()
    {
        return this.mtaLeases;
    }
    
    public void setMtaLeases(DCQArrayOfLeasesObj value)
    {
        this.mtaLeases = value;     
    }
    
    public DCQArrayOfMensajesObj getMensajes()
    {
        return this.mensajes;
    }
    
    public void setMensajes(DCQArrayOfMensajesObj value)
    {
        this.mensajes = value;     
    }
    
    public DCQArrayOfPoolingObj getPooling()
    {
        return this.pooling;
    }
    
    public void setPooling(DCQArrayOfPoolingObj value)
    {
        this.pooling = value;     
    }
    
    public DCQspDescriptionObj getSpDescription()
    {
        return this.spDescription;
    }
    
    public void setSpDescription(DCQspDescriptionObj value)
    {
        this.spDescription = value;     
    }
    
    public String getMtaCMSName()
    {
        return this.mtaCMSName;
    }
    
    public void setMtaCMSName(String value)
    {
        this.mtaCMSName = value;     
    }
    
    public String getMtaMacAddress()
    {
        return this.mtaMacAddress;
    }
    
    public void setMtaMacAddress(String value)
    {
        this.mtaMacAddress = value;     
    }
    
    public String getMtaHostname()
    {
        return this.mtaHostname;
    }
    
    public void setMtaHostname(String value)
    {
        this.mtaHostname = value;     
    }
    
    public String getMtaFQDN()
    {
        return this.mtaFQDN;
    }
    
    public void setMtaFQDN(String value)
    {
        this.mtaFQDN = value;     
    }
    
    public String getMtaIPAddress()
    {
        return this.mtaIPAddress;
    }
    
    public void setMtaIPAddress(String value)
    {
        this.mtaIPAddress = value;     
    }
    
    public String getPktcMtaDevProvStateCode()
    {
        return this.pktcMtaDevProvStateCode;
    }
    
    public void setPktcMtaDevProvStateCode(String value)
    {
        this.pktcMtaDevProvStateCode = value;     
    }
    
    public String getPktcMtaDevProvStateString()
    {
        return this.pktcMtaDevProvStateString;
    }
    
    public void setPktcMtaDevProvStateString(String value)
    {
        this.pktcMtaDevProvStateString = value;     
    }
    
    public String getEpStatus()
    {
        return this.epStatus;
    }
    
    public void setEpStatus(String value)
    {
        this.epStatus = value;     
    }
    
    public String getICmNetworkUsage()
    {
        return this.iCmNetworkUsage;
    }
    
    public void setICmNetworkUsage(String value)
    {
        this.iCmNetworkUsage = value;     
    }
    
    public String getIMtaNetworkUsage()
    {
        return this.iMtaNetworkUsage;
    }
    
    public void setIMtaNetworkUsage(String value)
    {
        this.iMtaNetworkUsage = value;     
    }
    
    public String getICpeNetworkUsage()
    {
        return this.iCpeNetworkUsage;
    }
    
    public void setICpeNetworkUsage(String value)
    {
        this.iCpeNetworkUsage = value;     
    }
    
    public String getCmActivationCode()
    {
        return this.cmActivationCode;
    }
    
    public void setCmActivationCode(String value)
    {
        this.cmActivationCode = value;     
    }
    
    public String getCmFechaAlta()
    {
        return this.cmFechaAlta;
    }
    
    public void setCmFechaAlta(String value)
    {
        this.cmFechaAlta = value;     
    }
    
    public String getCmFechaActivacion()
    {
        return this.cmFechaActivacion;
    }
    
    public void setCmFechaActivacion(String value)
    {
        this.cmFechaActivacion = value;     
    }
    
    public String getCmFechaModificacion()
    {
        return this.cmFechaModificacion;
    }
    
    public void setCmFechaModificacion(String value)
    {
        this.cmFechaModificacion = value;     
    }
    
    public String getMtaActivationCode()
    {
        return this.mtaActivationCode;
    }
    
    public void setMtaActivationCode(String value)
    {
        this.mtaActivationCode = value;     
    }
    
    public String getMtaFechaAlta()
    {
        return this.mtaFechaAlta;
    }
    
    public void setMtaFechaAlta(String value)
    {
        this.mtaFechaAlta = value;     
    }
    
    public String getMtaFechaActivacion()
    {
        return this.mtaFechaActivacion;
    }
    
    public void setMtaFechaActivacion(String value)
    {
        this.mtaFechaActivacion = value;     
    }
    
    public String getMtaFechaModificacion()
    {
        return this.mtaFechaModificacion;
    }
    
    public void setMtaFechaModificacion(String value)
    {
        this.mtaFechaModificacion = value;     
    }
    
    public String getSerialNumber()
    {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String value)
    {
        this.serialNumber = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("idClienteCRM"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idClienteCRM = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idClienteCRM = (String)obj;
                }
                else{
                    this.idClienteCRM = "";
                }
            }
            return true;
        }
        if (info.name.equals("nombre"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nombre = (String)obj;
                }
                else{
                    this.nombre = "";
                }
            }
            return true;
        }
        if (info.name.equals("username"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.username = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.username = (String)obj;
                }
                else{
                    this.username = "";
                }
            }
            return true;
        }
        if (info.name.equals("macaddress"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.macaddress = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.macaddress = (String)obj;
                }
                else{
                    this.macaddress = "";
                }
            }
            return true;
        }
        if (info.name.equals("productName"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.productName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.productName = (String)obj;
                }
                else{
                    this.productName = "";
                }
            }
            return true;
        }
        if (info.name.equals("manufacturer"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.manufacturer = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.manufacturer = (String)obj;
                }
                else{
                    this.manufacturer = "";
                }
            }
            return true;
        }
        if (info.name.equals("hwv"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.hwv = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.hwv = (String)obj;
                }
                else{
                    this.hwv = "";
                }
            }
            return true;
        }
        if (info.name.equals("swv"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.swv = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.swv = (String)obj;
                }
                else{
                    this.swv = "";
                }
            }
            return true;
        }
        if (info.name.equals("ip"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ip = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ip = (String)obj;
                }
                else{
                    this.ip = "";
                }
            }
            return true;
        }
        if (info.name.equals("cmts"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cmts = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cmts = (String)obj;
                }
                else{
                    this.cmts = "";
                }
            }
            return true;
        }
        if (info.name.equals("upStream"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.upStream = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.upStream = (String)obj;
                }
                else{
                    this.upStream = "";
                }
            }
            return true;
        }
        if (info.name.equals("downStream"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.downStream = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.downStream = (String)obj;
                }
                else{
                    this.downStream = "";
                }
            }
            return true;
        }
        if (info.name.equals("ispCM"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ispCM = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ispCM = (String)obj;
                }
                else{
                    this.ispCM = "";
                }
            }
            return true;
        }
        if (info.name.equals("ispMTA"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ispMTA = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ispMTA = (String)obj;
                }
                else{
                    this.ispMTA = "";
                }
            }
            return true;
        }
        if (info.name.equals("ispCPE"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ispCPE = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ispCPE = (String)obj;
                }
                else{
                    this.ispCPE = "";
                }
            }
            return true;
        }
        if (info.name.equals("servicePackage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.servicePackage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.servicePackage = (String)obj;
                }
                else{
                    this.servicePackage = "";
                }
            }
            return true;
        }
        if (info.name.equals("servicePackageID"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.servicePackageID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.servicePackageID = (String)obj;
                }
                else{
                    this.servicePackageID = "";
                }
            }
            return true;
        }
        if (info.name.equals("dpiPackage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dpiPackage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.dpiPackage = (String)obj;
                }
                else{
                    this.dpiPackage = "";
                }
            }
            return true;
        }
        if (info.name.equals("docsisVersion"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.docsisVersion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.docsisVersion = (String)obj;
                }
                else{
                    this.docsisVersion = "";
                }
            }
            return true;
        }
        if (info.name.equals("cantPCs"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cantPCs = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cantPCs = (String)obj;
                }
                else{
                    this.cantPCs = "";
                }
            }
            return true;
        }
        if (info.name.equals("disabled"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.disabled = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.disabled = (String)obj;
                }
                else{
                    this.disabled = "";
                }
            }
            return true;
        }
        if (info.name.equals("cantMensajes"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cantMensajes = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cantMensajes = (String)obj;
                }
                else{
                    this.cantMensajes = "";
                }
            }
            return true;
        }
        if (info.name.equals("upTraffic"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.upTraffic = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.upTraffic = (String)obj;
                }
                else{
                    this.upTraffic = "";
                }
            }
            return true;
        }
        if (info.name.equals("downTraffic"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.downTraffic = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.downTraffic = (String)obj;
                }
                else{
                    this.downTraffic = "";
                }
            }
            return true;
        }
        if (info.name.equals("hub"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.hub = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.hub = (String)obj;
                }
                else{
                    this.hub = "";
                }
            }
            return true;
        }
        if (info.name.equals("nodo"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nodo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nodo = (String)obj;
                }
                else{
                    this.nodo = "";
                }
            }
            return true;
        }
        if (info.name.equals("CmStatus"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CmStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CmStatus = (String)obj;
                }
                else{
                    this.CmStatus = "";
                }
            }
            return true;
        }
        if (info.name.equals("uspl"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.uspl = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.uspl = (String)obj;
                }
                else{
                    this.uspl = "";
                }
            }
            return true;
        }
        if (info.name.equals("dspl"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dspl = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.dspl = (String)obj;
                }
                else{
                    this.dspl = "";
                }
            }
            return true;
        }
        if (info.name.equals("dssnr"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dssnr = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.dssnr = (String)obj;
                }
                else{
                    this.dssnr = "";
                }
            }
            return true;
        }
        if (info.name.equals("ussnr"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ussnr = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ussnr = (String)obj;
                }
                else{
                    this.ussnr = "";
                }
            }
            return true;
        }
        if (info.name.equals("pollingSource"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pollingSource = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.pollingSource = (String)obj;
                }
                else{
                    this.pollingSource = "";
                }
            }
            return true;
        }
        if (info.name.equals("pollingDate"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pollingDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.pollingDate = (String)obj;
                }
                else{
                    this.pollingDate = "";
                }
            }
            return true;
        }
        if (info.name.equals("pollingage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pollingage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.pollingage = (String)obj;
                }
                else{
                    this.pollingage = "";
                }
            }
            return true;
        }
        if (info.name.equals("sysuptime"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.sysuptime = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.sysuptime = (String)obj;
                }
                else{
                    this.sysuptime = "";
                }
            }
            return true;
        }
        if (info.name.equals("status"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.status = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.status = (String)obj;
                }
                else{
                    this.status = "";
                }
            }
            return true;
        }
        if (info.name.equals("cmLeases"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.cmLeases = (DCQArrayOfLeasesObj)__envelope.get(j,DCQArrayOfLeasesObj.class,false);
            }
            return true;
        }
        if (info.name.equals("cpeLeases"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.cpeLeases = (DCQArrayOfLeasesObj)__envelope.get(j,DCQArrayOfLeasesObj.class,false);
            }
            return true;
        }
        if (info.name.equals("mtaLeases"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.mtaLeases = (DCQArrayOfLeasesObj)__envelope.get(j,DCQArrayOfLeasesObj.class,false);
            }
            return true;
        }
        if (info.name.equals("mensajes"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.mensajes = (DCQArrayOfMensajesObj)__envelope.get(j,DCQArrayOfMensajesObj.class,false);
            }
            return true;
        }
        if (info.name.equals("pooling"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.pooling = (DCQArrayOfPoolingObj)__envelope.get(j,DCQArrayOfPoolingObj.class,false);
            }
            return true;
        }
        if (info.name.equals("spDescription"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.spDescription = (DCQspDescriptionObj)__envelope.get(j,DCQspDescriptionObj.class,false);
            }
            return true;
        }
        if (info.name.equals("mtaCMSName"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaCMSName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaCMSName = (String)obj;
                }
                else{
                    this.mtaCMSName = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaMacAddress"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaMacAddress = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaMacAddress = (String)obj;
                }
                else{
                    this.mtaMacAddress = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaHostname"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaHostname = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaHostname = (String)obj;
                }
                else{
                    this.mtaHostname = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaFQDN"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaFQDN = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaFQDN = (String)obj;
                }
                else{
                    this.mtaFQDN = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaIPAddress"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaIPAddress = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaIPAddress = (String)obj;
                }
                else{
                    this.mtaIPAddress = "";
                }
            }
            return true;
        }
        if (info.name.equals("pktcMtaDevProvStateCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pktcMtaDevProvStateCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.pktcMtaDevProvStateCode = (String)obj;
                }
                else{
                    this.pktcMtaDevProvStateCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("pktcMtaDevProvStateString"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pktcMtaDevProvStateString = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.pktcMtaDevProvStateString = (String)obj;
                }
                else{
                    this.pktcMtaDevProvStateString = "";
                }
            }
            return true;
        }
        if (info.name.equals("epStatus"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.epStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.epStatus = (String)obj;
                }
                else{
                    this.epStatus = "";
                }
            }
            return true;
        }
        if (info.name.equals("iCmNetworkUsage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.iCmNetworkUsage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.iCmNetworkUsage = (String)obj;
                }
                else{
                    this.iCmNetworkUsage = "";
                }
            }
            return true;
        }
        if (info.name.equals("iMtaNetworkUsage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.iMtaNetworkUsage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.iMtaNetworkUsage = (String)obj;
                }
                else{
                    this.iMtaNetworkUsage = "";
                }
            }
            return true;
        }
        if (info.name.equals("iCpeNetworkUsage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.iCpeNetworkUsage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.iCpeNetworkUsage = (String)obj;
                }
                else{
                    this.iCpeNetworkUsage = "";
                }
            }
            return true;
        }
        if (info.name.equals("cmActivationCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cmActivationCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cmActivationCode = (String)obj;
                }
                else{
                    this.cmActivationCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("cmFechaAlta"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cmFechaAlta = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cmFechaAlta = (String)obj;
                }
                else{
                    this.cmFechaAlta = "";
                }
            }
            return true;
        }
        if (info.name.equals("cmFechaActivacion"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cmFechaActivacion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cmFechaActivacion = (String)obj;
                }
                else{
                    this.cmFechaActivacion = "";
                }
            }
            return true;
        }
        if (info.name.equals("cmFechaModificacion"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cmFechaModificacion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cmFechaModificacion = (String)obj;
                }
                else{
                    this.cmFechaModificacion = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaActivationCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaActivationCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaActivationCode = (String)obj;
                }
                else{
                    this.mtaActivationCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaFechaAlta"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaFechaAlta = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaFechaAlta = (String)obj;
                }
                else{
                    this.mtaFechaAlta = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaFechaActivacion"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaFechaActivacion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaFechaActivacion = (String)obj;
                }
                else{
                    this.mtaFechaActivacion = "";
                }
            }
            return true;
        }
        if (info.name.equals("mtaFechaModificacion"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.mtaFechaModificacion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.mtaFechaModificacion = (String)obj;
                }
                else{
                    this.mtaFechaModificacion = "";
                }
            }
            return true;
        }
        if (info.name.equals("serialNumber"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.serialNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.serialNumber = (String)obj;
                }
                else{
                    this.serialNumber = "";
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.idClienteCRM!=null?this.idClienteCRM:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.nombre!=null?this.nombre:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.username!=null?this.username:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.macaddress!=null?this.macaddress:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.productName!=null?this.productName:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.manufacturer!=null?this.manufacturer:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.hwv!=null?this.hwv:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.swv!=null?this.swv:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==8)
        {
            return this.ip!=null?this.ip:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==9)
        {
            return this.cmts!=null?this.cmts:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==10)
        {
            return this.upStream!=null?this.upStream:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==11)
        {
            return this.downStream!=null?this.downStream:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==12)
        {
            return this.ispCM!=null?this.ispCM:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==13)
        {
            return this.ispMTA!=null?this.ispMTA:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==14)
        {
            return this.ispCPE!=null?this.ispCPE:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==15)
        {
            return this.servicePackage!=null?this.servicePackage:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==16)
        {
            return this.servicePackageID!=null?this.servicePackageID:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==17)
        {
            return this.dpiPackage!=null?this.dpiPackage:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==18)
        {
            return this.docsisVersion!=null?this.docsisVersion:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==19)
        {
            return this.cantPCs!=null?this.cantPCs:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==20)
        {
            return this.disabled!=null?this.disabled:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==21)
        {
            return this.cantMensajes!=null?this.cantMensajes:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==22)
        {
            return this.upTraffic!=null?this.upTraffic:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==23)
        {
            return this.downTraffic!=null?this.downTraffic:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==24)
        {
            return this.hub!=null?this.hub:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==25)
        {
            return this.nodo!=null?this.nodo:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==26)
        {
            return this.CmStatus!=null?this.CmStatus:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==27)
        {
            return this.uspl!=null?this.uspl:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==28)
        {
            return this.dspl!=null?this.dspl:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==29)
        {
            return this.dssnr!=null?this.dssnr:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==30)
        {
            return this.ussnr!=null?this.ussnr:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==31)
        {
            return this.pollingSource!=null?this.pollingSource:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==32)
        {
            return this.pollingDate!=null?this.pollingDate:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==33)
        {
            return this.pollingage!=null?this.pollingage:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==34)
        {
            return this.sysuptime!=null?this.sysuptime:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==35)
        {
            return this.status!=null?this.status:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==36)
        {
            return this.cmLeases!=null?this.cmLeases:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==37)
        {
            return this.cpeLeases!=null?this.cpeLeases:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==38)
        {
            return this.mtaLeases!=null?this.mtaLeases:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==39)
        {
            return this.mensajes!=null?this.mensajes:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==40)
        {
            return this.pooling!=null?this.pooling:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==41)
        {
            return this.spDescription!=null?this.spDescription:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==42)
        {
            return this.mtaCMSName!=null?this.mtaCMSName:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==43)
        {
            return this.mtaMacAddress!=null?this.mtaMacAddress:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==44)
        {
            return this.mtaHostname!=null?this.mtaHostname:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==45)
        {
            return this.mtaFQDN!=null?this.mtaFQDN:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==46)
        {
            return this.mtaIPAddress!=null?this.mtaIPAddress:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==47)
        {
            return this.pktcMtaDevProvStateCode!=null?this.pktcMtaDevProvStateCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==48)
        {
            return this.pktcMtaDevProvStateString!=null?this.pktcMtaDevProvStateString:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==49)
        {
            return this.epStatus!=null?this.epStatus:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==50)
        {
            return this.iCmNetworkUsage!=null?this.iCmNetworkUsage:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==51)
        {
            return this.iMtaNetworkUsage!=null?this.iMtaNetworkUsage:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==52)
        {
            return this.iCpeNetworkUsage!=null?this.iCpeNetworkUsage:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==53)
        {
            return this.cmActivationCode!=null?this.cmActivationCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==54)
        {
            return this.cmFechaAlta!=null?this.cmFechaAlta:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==55)
        {
            return this.cmFechaActivacion!=null?this.cmFechaActivacion:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==56)
        {
            return this.cmFechaModificacion!=null?this.cmFechaModificacion:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==57)
        {
            return this.mtaActivationCode!=null?this.mtaActivationCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==58)
        {
            return this.mtaFechaAlta!=null?this.mtaFechaAlta:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==59)
        {
            return this.mtaFechaActivacion!=null?this.mtaFechaActivacion:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==60)
        {
            return this.mtaFechaModificacion!=null?this.mtaFechaModificacion:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==61)
        {
            return this.serialNumber!=null?this.serialNumber:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 62;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idClienteCRM";
            info.namespace= "";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nombre";
            info.namespace= "";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "username";
            info.namespace= "";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "macaddress";
            info.namespace= "";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "productName";
            info.namespace= "";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "manufacturer";
            info.namespace= "";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "hwv";
            info.namespace= "";
        }
        else if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "swv";
            info.namespace= "";
        }
        else if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ip";
            info.namespace= "";
        }
        else if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cmts";
            info.namespace= "";
        }
        else if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "upStream";
            info.namespace= "";
        }
        else if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "downStream";
            info.namespace= "";
        }
        else if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ispCM";
            info.namespace= "";
        }
        else if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ispMTA";
            info.namespace= "";
        }
        else if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ispCPE";
            info.namespace= "";
        }
        else if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "servicePackage";
            info.namespace= "";
        }
        else if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "servicePackageID";
            info.namespace= "";
        }
        else if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dpiPackage";
            info.namespace= "";
        }
        else if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "docsisVersion";
            info.namespace= "";
        }
        else if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cantPCs";
            info.namespace= "";
        }
        else if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "disabled";
            info.namespace= "";
        }
        else if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cantMensajes";
            info.namespace= "";
        }
        else if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "upTraffic";
            info.namespace= "";
        }
        else if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "downTraffic";
            info.namespace= "";
        }
        else if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "hub";
            info.namespace= "";
        }
        else if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nodo";
            info.namespace= "";
        }
        else if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CmStatus";
            info.namespace= "";
        }
        else if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "uspl";
            info.namespace= "";
        }
        else if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dspl";
            info.namespace= "";
        }
        else if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dssnr";
            info.namespace= "";
        }
        else if(propertyIndex==30)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ussnr";
            info.namespace= "";
        }
        else if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pollingSource";
            info.namespace= "";
        }
        else if(propertyIndex==32)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pollingDate";
            info.namespace= "";
        }
        else if(propertyIndex==33)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pollingage";
            info.namespace= "";
        }
        else if(propertyIndex==34)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "sysuptime";
            info.namespace= "";
        }
        else if(propertyIndex==35)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "status";
            info.namespace= "";
        }
        else if(propertyIndex==36)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "cmLeases";
            info.namespace= "";
        }
        else if(propertyIndex==37)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "cpeLeases";
            info.namespace= "";
        }
        else if(propertyIndex==38)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "mtaLeases";
            info.namespace= "";
        }
        else if(propertyIndex==39)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "mensajes";
            info.namespace= "";
        }
        else if(propertyIndex==40)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "pooling";
            info.namespace= "";
        }
        else if(propertyIndex==41)
        {
            info.type = DCQspDescriptionObj.class;
            info.name = "spDescription";
            info.namespace= "";
        }
        else if(propertyIndex==42)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaCMSName";
            info.namespace= "";
        }
        else if(propertyIndex==43)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaMacAddress";
            info.namespace= "";
        }
        else if(propertyIndex==44)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaHostname";
            info.namespace= "";
        }
        else if(propertyIndex==45)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaFQDN";
            info.namespace= "";
        }
        else if(propertyIndex==46)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaIPAddress";
            info.namespace= "";
        }
        else if(propertyIndex==47)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pktcMtaDevProvStateCode";
            info.namespace= "";
        }
        else if(propertyIndex==48)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pktcMtaDevProvStateString";
            info.namespace= "";
        }
        else if(propertyIndex==49)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "epStatus";
            info.namespace= "";
        }
        else if(propertyIndex==50)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "iCmNetworkUsage";
            info.namespace= "";
        }
        else if(propertyIndex==51)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "iMtaNetworkUsage";
            info.namespace= "";
        }
        else if(propertyIndex==52)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "iCpeNetworkUsage";
            info.namespace= "";
        }
        else if(propertyIndex==53)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cmActivationCode";
            info.namespace= "";
        }
        else if(propertyIndex==54)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cmFechaAlta";
            info.namespace= "";
        }
        else if(propertyIndex==55)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cmFechaActivacion";
            info.namespace= "";
        }
        else if(propertyIndex==56)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cmFechaModificacion";
            info.namespace= "";
        }
        else if(propertyIndex==57)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaActivationCode";
            info.namespace= "";
        }
        else if(propertyIndex==58)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaFechaAlta";
            info.namespace= "";
        }
        else if(propertyIndex==59)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaFechaActivacion";
            info.namespace= "";
        }
        else if(propertyIndex==60)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "mtaFechaModificacion";
            info.namespace= "";
        }
        else if(propertyIndex==61)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "serialNumber";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
