package com.iwy.wsdl.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------


import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;



//If you have a compilation error here then you have to add a reference to ExKsoap2.jar to your project (you can find it in Libs folder in the generated zip file)
public class DCQExtendedSoapSerializationEnvelope extends com.easywsdl.exksoap2.serialization.ExSoapSerializationEnvelope {
    static HashMap< java.lang.String,java.lang.Class> classNames = new HashMap< java.lang.String, java.lang.Class>();
    
    static {
        classNames.put("urn:IntrawayWSDL^^InterfaceObjInput",DCQInterfaceObjInput.class);
        classNames.put("urn:IntrawayWSDL^^InterfaceObjOutput",DCQInterfaceObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^InternalObjOutput",DCQInternalObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^createTempMTAInput",DCQcreateTempMTAInput.class);
        classNames.put("urn:IntrawayWSDL^^createTempSIPDeviceInput",DCQcreateTempSIPDeviceInput.class);
        classNames.put("urn:IntrawayWSDL^^createTempMTAOutput",DCQcreateTempMTAOutput.class);
        classNames.put("urn:IntrawayWSDL^^createTempSIPDeviceOutput",DCQcreateTempSIPDeviceOutput.class);
        classNames.put("urn:IntrawayWSDL^^activateADSLInput",DCQactivateADSLInput.class);
        classNames.put("urn:IntrawayWSDL^^activateADSLOutput",DCQactivateADSLOutput.class);
        classNames.put("urn:IntrawayWSDL^^leasesObj",DCQleasesObj.class);
        classNames.put("urn:IntrawayWSDL^^mensajesObj",DCQmensajesObj.class);
        classNames.put("urn:IntrawayWSDL^^spDescriptionObj",DCQspDescriptionObj.class);
        classNames.put("urn:IntrawayWSDL^^comandosObj",DCQcomandosObj.class);
        classNames.put("urn:IntrawayWSDL^^opcionesObj",DCQopcionesObj.class);
        classNames.put("urn:IntrawayWSDL^^flowsObj",DCQflowsObj.class);
        classNames.put("urn:IntrawayWSDL^^poolingObj",DCQpoolingObj.class);
        classNames.put("urn:IntrawayWSDL^^ActivityObjOutput",DCQActivityObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^DocsisStatusObjOutput",DCQDocsisStatusObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^MaintenanceObjInput",DCQMaintenanceObjInput.class);
        classNames.put("urn:IntrawayWSDL^^MaintenanceObjOutput",DCQMaintenanceObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfActivityObjOutput",DCQArrayOfActivityObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfComandosObj",DCQArrayOfComandosObj.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfOpcionesObj",DCQArrayOfOpcionesObj.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfFlowsObj",DCQArrayOfFlowsObj.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfInterfaceObjInput",DCQArrayOfInterfaceObjInput.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfLeasesObj",DCQArrayOfLeasesObj.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfMensajesObj",DCQArrayOfMensajesObj.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfInterfaceObjOutput",DCQArrayOfInterfaceObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfPoolingObj",DCQArrayOfPoolingObj.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfMaintenanceObjOutput",DCQArrayOfMaintenanceObjOutput.class);
        classNames.put("urn:IntrawayWSDL^^ArrayOfMaintenanceObjInput",DCQArrayOfMaintenanceObjInput.class);
    } 

    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public static void setDateTimeConverter(DCQDateTimeConverter converter)
    {
        if(converter==null)
        {
            dateTimeConverter = new DCQStandardDateTimeConverter();
        }
        dateTimeConverter=converter;
    }

    public static DCQDateTimeConverter getDateTimeConverter()
    {
        return dateTimeConverter;
    }

    private static DCQDateTimeConverter dateTimeConverter = new DCQStandardDateTimeConverter();

    public DCQExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public DCQExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new DCQMarshalGuid().register(this);
        new MarshalFloat().register(this);
    }


    @Override
    protected void writeProperty(XmlSerializer writer, java.lang.Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        if(writeReferenceObject(writer,obj))
        {
            return;
        }
        java.lang.Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {
            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=java.lang.String.class  )) {
                java.lang.String xmlName=DCQHelper.getKeyByValue(classNames,obj.getClass());
                if(xmlName!=null) {
                    java.lang.String[] parts = xmlName.split("\\^\\^");
                    java.lang.String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        java.lang.String xsdPrefix = writer.getPrefix(xsd, true);
                        java.lang.String myType = (java.lang.String) type.type;
                        java.lang.String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        java.lang.String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }

    public SoapObject GetExceptionDetail(Element detailElement,java.lang.String exceptionElementNS,java.lang.String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public java.lang.Object GetHeader(Element detailElement) {
        if(detailElement.getChildCount()>0 && detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    private Object createObject(Object soap, Class cl) throws InstantiationException, IllegalAccessException, NoSuchMethodException, InvocationTargetException {
        Object obj=cl.newInstance();
        Method ctor = obj.getClass().getMethod("loadFromSoap",Object.class,DCQExtendedSoapSerializationEnvelope.class);
        ctor.invoke(obj,soap,this);
        return obj;
    }

    public java.lang.Object get(java.lang.Object soap,java.lang.Class cl,boolean typeFromClass)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(typeFromClass)
            {
                return createObject(soap, cl);
            }
            java.lang.Object refAttr=getReference(soap);
            if (refAttr != null)
            {
                return refAttr;
            }
            else
            {
                if(soap instanceof SoapObject)
                {
                    if(cl ==SoapObject.class)
                    {
                        return soap;
                    }
                    java.lang.String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                return createObject(soap, cl);
            }
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }


    public java.lang.Object getSpecificType(java.lang.Object obj)
    {
        if(obj==null)
        {
            return null;
        }
        if(obj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)obj;
            java.lang.String key=soapObject.getNamespace()+"^^"+soapObject.getName();
            if(classNames.containsKey(key))
            {
                java.lang.Class cl=classNames.get(key);
                try
                {
                    return createObject(soapObject, cl);
                } 
                catch (java.lang.Exception e)
                {
                    e.printStackTrace();
                }
            }
        }

        return obj;
    }

    public static java.lang.Object getXSDType(java.lang.Object param)
    {
        if(param==null)
        {
            return null;
        }
        java.lang.Class obj=param.getClass();
        if(obj.equals(java.lang.String.class))
        {
            return "string";
        }
        if(obj.equals(int.class) || obj.equals(java.lang.Integer.class))
        {
            return "int";
        }
        if(obj.equals(float.class) || obj.equals(java.lang.Float.class))
        {
            return "float";
        }
        if(obj.equals(double.class) || obj.equals(java.lang.Double.class))
        {
            return "double";
        }
        if(obj.equals(java.math.BigDecimal.class))
        {
            return "decimal";
        }
        if(obj.equals(short.class) || obj.equals(java.lang.Short.class))
        {
            return "short";
        }
        if(obj.equals(long.class) || obj.equals(java.lang.Long.class))
        {
            return "long";
        }
        if(obj.equals(boolean.class) || obj.equals(java.lang.Boolean.class))
        {
            return "boolean";
        }
        java.lang.String xmlName=DCQHelper.getKeyByValue(classNames,obj);
        if(xmlName==null)
        {
            return obj;
        }
        return xmlName;
    }} 

