package com.iwy.wsdl.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------





import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class DCQIntrawayWSDLBinding
{
    interface DCQIWcfMethod
    {
        DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://172.16.120.40/IntrawayWS/server.php";

    int timeOut=60000;
    private List< HeaderProperty> httpHeaders= new ArrayList< HeaderProperty>();
    private boolean enableLogging;


    public List< HeaderProperty> getHttpHeaders()
    {
        return this.httpHeaders;
    }
    
    public boolean getEnableLogging()
    {
        return this.enableLogging;
    }
    
    public void setEnableLogging(boolean value)
    {
        this.enableLogging=value;
    }
    

    
    public DCQIntrawayWSDLBinding(){}

    public DCQIntrawayWSDLBinding(String url)
    {
        this.url = url;
    }

    public DCQIntrawayWSDLBinding(String url,int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                String path=uri.getPath();
                if(uri.getQuery()!=null && uri.getQuery()!="")
                {
                    path+="?"+uri.getQuery();
                }
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, path, timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }

    protected DCQExtendedSoapSerializationEnvelope createEnvelope()
    {
        DCQExtendedSoapSerializationEnvelope envelope= new DCQExtendedSoapSerializationEnvelope(DCQExtendedSoapSerializationEnvelope.VER11);
            return envelope;
    }

    protected java.util.List sendRequest(String methodName,DCQExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,DCQExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) 
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }

        return null;
    }

    
    
    
    public DCQArrayOfInterfaceObjOutput Put(final String authKey,final DCQArrayOfInterfaceObjInput ArrayOfInterfaceObjInput,final String doAtomic) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQArrayOfInterfaceObjOutput)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("","ArrayOfInterfaceObjInput",DCQArrayOfInterfaceObjInput.class);
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "Put");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="ArrayOfInterfaceObjInput";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(ArrayOfInterfaceObjInput!=null?ArrayOfInterfaceObjInput:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="doAtomic";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(doAtomic!=null?doAtomic:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQArrayOfInterfaceObjOutput)getResult(DCQArrayOfInterfaceObjOutput.class,__result,"ArrayOfInterfaceObjOutput",__envelope);
            }
        },"urn:IntrawayWSDL#Put",__profile);
    }
    
    
    
    public DCQGetActivityResponse GetActivity(final String authKey,final String xmlEncoding) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQGetActivityResponse)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "GetActivity");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="xmlEncoding";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(xmlEncoding!=null?xmlEncoding:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQGetActivityResponse)getResult(DCQGetActivityResponse.class,__result,"GetActivityResponse",__envelope);
            }
        },"urn:IntrawayWSDL#GetActivity",__profile);
    }
    
    
    
    public DCQGetDocsisStatusResponse GetDocsisStatus(final String authKey,final String idEmpresaCRM,final String idServicio,final String idVenta,final String idProducto,final String xmlEncoding) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQGetDocsisStatusResponse)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "GetDocsisStatus");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="idEmpresaCRM";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idEmpresaCRM!=null?idEmpresaCRM:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="idServicio";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idServicio!=null?idServicio:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="idVenta";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idVenta!=null?idVenta:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="idProducto";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idProducto!=null?idProducto:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="xmlEncoding";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(xmlEncoding!=null?xmlEncoding:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQGetDocsisStatusResponse)getResult(DCQGetDocsisStatusResponse.class,__result,"GetDocsisStatusResponse",__envelope);
            }
        },"urn:IntrawayWSDL#GetDocsisStatus",__profile);
    }
    
    
    
    public DCQArrayOfMaintenanceObjOutput Maintenance(final String authKey,final DCQArrayOfMaintenanceObjInput ArrayOfMaintenanceObjInput) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQArrayOfMaintenanceObjOutput)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("","ArrayOfMaintenanceObjInput",DCQArrayOfMaintenanceObjInput.class);
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "Maintenance");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="ArrayOfMaintenanceObjInput";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(ArrayOfMaintenanceObjInput!=null?ArrayOfMaintenanceObjInput:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQArrayOfMaintenanceObjOutput)getResult(DCQArrayOfMaintenanceObjOutput.class,__result,"ArrayOfMaintenanceObjOutput",__envelope);
            }
        },"urn:IntrawayWSDL#Maintenance",__profile);
    }
    
    
    
    public DCQInternalObjOutput Internal(final String authKey,final String xmlEncoding) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQInternalObjOutput)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "Internal");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="xmlEncoding";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(xmlEncoding!=null?xmlEncoding:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQInternalObjOutput)getResult(DCQInternalObjOutput.class,__result,"Output",__envelope);
            }
        },"urn:IntrawayWSDL#Internal",__profile);
    }
    
    
    
    public DCQcreateTempMTAOutput createTempMTA(final String authKey,final DCQcreateTempMTAInput Input) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQcreateTempMTAOutput)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("","Input",DCQcreateTempMTAInput.class);
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "createTempMTA");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="Input";
                __info.type=DCQcreateTempMTAInput.class;
                __info.setValue(Input!=null?Input:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQcreateTempMTAOutput)getResult(DCQcreateTempMTAOutput.class,__result,"Output",__envelope);
            }
        },"urn:IntrawayWSDL#createTempMTA",__profile);
    }
    
    
    
    public DCQcreateTempSIPDeviceOutput createTempSIPDevice(final String authKey,final DCQcreateTempSIPDeviceInput Input) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQcreateTempSIPDeviceOutput)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("","Input",DCQcreateTempSIPDeviceInput.class);
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "createTempSIPDevice");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="Input";
                __info.type=DCQcreateTempSIPDeviceInput.class;
                __info.setValue(Input!=null?Input:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQcreateTempSIPDeviceOutput)getResult(DCQcreateTempSIPDeviceOutput.class,__result,"Output",__envelope);
            }
        },"urn:IntrawayWSDL#createTempSIPDevice",__profile);
    }
    
    
    
    public DCQactivateADSLOutput activateADSL(final String authKey,final DCQactivateADSLInput Input) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DCQactivateADSLOutput)execute(new DCQIWcfMethod()
        {
            @Override
            public DCQExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                DCQExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("","Input",DCQactivateADSLInput.class);
                SoapObject __soapReq = new SoapObject("urn:IntrawayWSDL", "activateADSL");
                __soapReq.addAttribute("http://schemas.xmlsoap.org/soap/envelope/","encodingStyle","http://schemas.xmlsoap.org/soap/encoding/");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="authKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(authKey!=null?authKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="Input";
                __info.type=DCQactivateADSLInput.class;
                __info.setValue(Input!=null?Input:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(DCQExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (DCQactivateADSLOutput)getResult(DCQactivateADSLOutput.class,__result,"Output",__envelope);
            }
        },"urn:IntrawayWSDL#activateADSL",__profile);
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String GetReport(final String authKey,final String idEmpresaCRM,final String idClienteCRM,final String cantRecords,final String showProducts) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String GetCustomReport(final String authKey,final String showProducts) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String GetDocsisTrafficReport(final String authKey,final String idEmpresaCRM,final String idClienteCRM,final String cantRecords,final String fromDate,final String toDate) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String Audit(final String authKey,final String idEmpresaCRM,final String idClienteCRM,final String cantRecords,final String xmlEncoding) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String GetPPVReport(final String authKey,final String idClienteCRM,final String idEmpresaCRM,final String idProducto,final String idVenta,final String idServicio,final String controllerType,final String controllerCRMId,final String purchaseId,final String cantRecords,final String xmlEncoding) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String GetPPVCatalog(final String authKey,final String idEmpresa,final String controllerType,final String cantRecords,final String xmlEncoding) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String GetPPVMenu(final String authKey,final String xmlEncoding) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String GetPPVTickets(final String authKey,final String ticketId,final String cantRecords,final String xmlEncoding) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }

    protected java.lang.Object execute(DCQIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        DCQExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    System.out.println("requestDump: "+__httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    System.out.println("responseDump: "+__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }


    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault,DCQExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;
                return newException;
    }
}


