package com.iwy.wsdl.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DCQInterfaceObjInput extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String idEntradaCaller;
    
    private String idInterface;
    
    private String idEstado;
    
    private String asyncronic;
    
    private String fechaDiferido;
    
    private String idCliente;
    
    private String idEmpresa;
    
    private String idVenta;
    
    private String idVentaPadre;
    
    private String idServicio;
    
    private String idProducto;
    
    private String idServicioPadre;
    
    private String idProductoPadre;
    
    private String idPromotor;
    
    private String xmlEncoding;
    
    public String getIdEntradaCaller()
    {
        return this.idEntradaCaller;
    }
    
    public void setIdEntradaCaller(String value)
    {
        this.idEntradaCaller = value;     
    }
    
    public String getIdInterface()
    {
        return this.idInterface;
    }
    
    public void setIdInterface(String value)
    {
        this.idInterface = value;     
    }
    
    public String getIdEstado()
    {
        return this.idEstado;
    }
    
    public void setIdEstado(String value)
    {
        this.idEstado = value;     
    }
    
    public String getAsyncronic()
    {
        return this.asyncronic;
    }
    
    public void setAsyncronic(String value)
    {
        this.asyncronic = value;     
    }
    
    public String getFechaDiferido()
    {
        return this.fechaDiferido;
    }
    
    public void setFechaDiferido(String value)
    {
        this.fechaDiferido = value;     
    }
    
    public String getIdCliente()
    {
        return this.idCliente;
    }
    
    public void setIdCliente(String value)
    {
        this.idCliente = value;     
    }
    
    public String getIdEmpresa()
    {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(String value)
    {
        this.idEmpresa = value;     
    }
    
    public String getIdVenta()
    {
        return this.idVenta;
    }
    
    public void setIdVenta(String value)
    {
        this.idVenta = value;     
    }
    
    public String getIdVentaPadre()
    {
        return this.idVentaPadre;
    }
    
    public void setIdVentaPadre(String value)
    {
        this.idVentaPadre = value;     
    }
    
    public String getIdServicio()
    {
        return this.idServicio;
    }
    
    public void setIdServicio(String value)
    {
        this.idServicio = value;     
    }
    
    public String getIdProducto()
    {
        return this.idProducto;
    }
    
    public void setIdProducto(String value)
    {
        this.idProducto = value;     
    }
    
    public String getIdServicioPadre()
    {
        return this.idServicioPadre;
    }
    
    public void setIdServicioPadre(String value)
    {
        this.idServicioPadre = value;     
    }
    
    public String getIdProductoPadre()
    {
        return this.idProductoPadre;
    }
    
    public void setIdProductoPadre(String value)
    {
        this.idProductoPadre = value;     
    }
    
    public String getIdPromotor()
    {
        return this.idPromotor;
    }
    
    public void setIdPromotor(String value)
    {
        this.idPromotor = value;     
    }
    
    public String getXmlEncoding()
    {
        return this.xmlEncoding;
    }
    
    public void setXmlEncoding(String value)
    {
        this.xmlEncoding = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("idEntradaCaller"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idEntradaCaller = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idEntradaCaller = (String)obj;
                }
                else{
                    this.idEntradaCaller = "";
                }
            }
            return true;
        }
        if (info.name.equals("idInterface"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idInterface = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idInterface = (String)obj;
                }
                else{
                    this.idInterface = "";
                }
            }
            return true;
        }
        if (info.name.equals("idEstado"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idEstado = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idEstado = (String)obj;
                }
                else{
                    this.idEstado = "";
                }
            }
            return true;
        }
        if (info.name.equals("asyncronic"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.asyncronic = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.asyncronic = (String)obj;
                }
                else{
                    this.asyncronic = "";
                }
            }
            return true;
        }
        if (info.name.equals("fechaDiferido"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.fechaDiferido = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.fechaDiferido = (String)obj;
                }
                else{
                    this.fechaDiferido = "";
                }
            }
            return true;
        }
        if (info.name.equals("idCliente"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idCliente = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idCliente = (String)obj;
                }
                else{
                    this.idCliente = "";
                }
            }
            return true;
        }
        if (info.name.equals("idEmpresa"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idEmpresa = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idEmpresa = (String)obj;
                }
                else{
                    this.idEmpresa = "";
                }
            }
            return true;
        }
        if (info.name.equals("idVenta"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idVenta = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idVenta = (String)obj;
                }
                else{
                    this.idVenta = "";
                }
            }
            return true;
        }
        if (info.name.equals("idVentaPadre"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idVentaPadre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idVentaPadre = (String)obj;
                }
                else{
                    this.idVentaPadre = "";
                }
            }
            return true;
        }
        if (info.name.equals("idServicio"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idServicio = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idServicio = (String)obj;
                }
                else{
                    this.idServicio = "";
                }
            }
            return true;
        }
        if (info.name.equals("idProducto"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idProducto = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idProducto = (String)obj;
                }
                else{
                    this.idProducto = "";
                }
            }
            return true;
        }
        if (info.name.equals("idServicioPadre"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idServicioPadre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idServicioPadre = (String)obj;
                }
                else{
                    this.idServicioPadre = "";
                }
            }
            return true;
        }
        if (info.name.equals("idProductoPadre"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idProductoPadre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idProductoPadre = (String)obj;
                }
                else{
                    this.idProductoPadre = "";
                }
            }
            return true;
        }
        if (info.name.equals("idPromotor"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idPromotor = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idPromotor = (String)obj;
                }
                else{
                    this.idPromotor = "";
                }
            }
            return true;
        }
        if (info.name.equals("xmlEncoding"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.xmlEncoding = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.xmlEncoding = (String)obj;
                }
                else{
                    this.xmlEncoding = "";
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.idEntradaCaller;
        }
        else if(propertyIndex==1)
        {
            return this.idInterface;
        }
        else if(propertyIndex==2)
        {
            return this.idEstado;
        }
        else if(propertyIndex==3)
        {
            return this.asyncronic;
        }
        else if(propertyIndex==4)
        {
            return this.fechaDiferido;
        }
        else if(propertyIndex==5)
        {
            return this.idCliente;
        }
        else if(propertyIndex==6)
        {
            return this.idEmpresa;
        }
        else if(propertyIndex==7)
        {
            return this.idVenta;
        }
        else if(propertyIndex==8)
        {
            return this.idVentaPadre;
        }
        else if(propertyIndex==9)
        {
            return this.idServicio;
        }
        else if(propertyIndex==10)
        {
            return this.idProducto;
        }
        else if(propertyIndex==11)
        {
            return this.idServicioPadre;
        }
        else if(propertyIndex==12)
        {
            return this.idProductoPadre;
        }
        else if(propertyIndex==13)
        {
            return this.idPromotor;
        }
        else if(propertyIndex==14)
        {
            return this.xmlEncoding;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 15;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idEntradaCaller";
            info.namespace= "";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idInterface";
            info.namespace= "";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idEstado";
            info.namespace= "";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "asyncronic";
            info.namespace= "";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fechaDiferido";
            info.namespace= "";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idCliente";
            info.namespace= "";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idEmpresa";
            info.namespace= "";
        }
        else if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idVenta";
            info.namespace= "";
        }
        else if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idVentaPadre";
            info.namespace= "";
        }
        else if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idServicio";
            info.namespace= "";
        }
        else if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idProducto";
            info.namespace= "";
        }
        else if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idServicioPadre";
            info.namespace= "";
        }
        else if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idProductoPadre";
            info.namespace= "";
        }
        else if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idPromotor";
            info.namespace= "";
        }
        else if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "xmlEncoding";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
