package com.iwy.wsdl.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DCQleasesObj extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String fecha;
    
    private String ip;
    
    private String macaddress;
    
    private String manufacturer;
    
    private String online;
    
    public String getFecha()
    {
        return this.fecha;
    }
    
    public void setFecha(String value)
    {
        this.fecha = value;     
    }
    
    public String getIp()
    {
        return this.ip;
    }
    
    public void setIp(String value)
    {
        this.ip = value;     
    }
    
    public String getMacaddress()
    {
        return this.macaddress;
    }
    
    public void setMacaddress(String value)
    {
        this.macaddress = value;     
    }
    
    public String getManufacturer()
    {
        return this.manufacturer;
    }
    
    public void setManufacturer(String value)
    {
        this.manufacturer = value;     
    }
    
    public String getOnline()
    {
        return this.online;
    }
    
    public void setOnline(String value)
    {
        this.online = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("fecha"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.fecha = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.fecha = (String)obj;
                }
                else{
                    this.fecha = "";
                }
            }
            return true;
        }
        if (info.name.equals("ip"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ip = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ip = (String)obj;
                }
                else{
                    this.ip = "";
                }
            }
            return true;
        }
        if (info.name.equals("macaddress"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.macaddress = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.macaddress = (String)obj;
                }
                else{
                    this.macaddress = "";
                }
            }
            return true;
        }
        if (info.name.equals("manufacturer"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.manufacturer = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.manufacturer = (String)obj;
                }
                else{
                    this.manufacturer = "";
                }
            }
            return true;
        }
        if (info.name.equals("online"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.online = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.online = (String)obj;
                }
                else{
                    this.online = "";
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.fecha;
        }
        else if(propertyIndex==1)
        {
            return this.ip;
        }
        else if(propertyIndex==2)
        {
            return this.macaddress;
        }
        else if(propertyIndex==3)
        {
            return this.manufacturer;
        }
        else if(propertyIndex==4)
        {
            return this.online;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fecha";
            info.namespace= "";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ip";
            info.namespace= "";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "macaddress";
            info.namespace= "";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "manufacturer";
            info.namespace= "";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "online";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
