package com.iwy.wsdl.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DCQmensajesObj extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String idMensajeCRM;
    
    private String nombre;
    
    private String descripcion;
    
    private String removible;
    
    public String getIdMensajeCRM()
    {
        return this.idMensajeCRM;
    }
    
    public void setIdMensajeCRM(String value)
    {
        this.idMensajeCRM = value;     
    }
    
    public String getNombre()
    {
        return this.nombre;
    }
    
    public void setNombre(String value)
    {
        this.nombre = value;     
    }
    
    public String getDescripcion()
    {
        return this.descripcion;
    }
    
    public void setDescripcion(String value)
    {
        this.descripcion = value;     
    }
    
    public String getRemovible()
    {
        return this.removible;
    }
    
    public void setRemovible(String value)
    {
        this.removible = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("idMensajeCRM"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.idMensajeCRM = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.idMensajeCRM = (String)obj;
                }
                else{
                    this.idMensajeCRM = "";
                }
            }
            return true;
        }
        if (info.name.equals("nombre"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nombre = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nombre = (String)obj;
                }
                else{
                    this.nombre = "";
                }
            }
            return true;
        }
        if (info.name.equals("descripcion"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.descripcion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.descripcion = (String)obj;
                }
                else{
                    this.descripcion = "";
                }
            }
            return true;
        }
        if (info.name.equals("removible"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.removible = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.removible = (String)obj;
                }
                else{
                    this.removible = "";
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.idMensajeCRM;
        }
        else if(propertyIndex==1)
        {
            return this.nombre;
        }
        else if(propertyIndex==2)
        {
            return this.descripcion;
        }
        else if(propertyIndex==3)
        {
            return this.removible;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "idMensajeCRM";
            info.namespace= "";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nombre";
            info.namespace= "";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "descripcion";
            info.namespace= "";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "removible";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
