package com.iwy.wsdl.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DCQpoolingObj extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String cmPoolingId;
    
    private String firstPoolingDate;
    
    private String lastPoolingDate;
    
    private String repetitions;
    
    private String lastTimeoutDate;
    
    private String totalTimeouts;
    
    private String dsPower;
    
    private String usPower;
    
    private String dsSNR;
    
    private String upSNR;
    
    private String downChannel;
    
    private String upChannel;
    
    private String rxPower;
    
    private String dsGoodCW;
    
    private String dsCorrectableCW;
    
    private String lastDSGoodCW;
    
    private String lastDSCorrectableCW;
    
    private String lastDSUnCorrectableCW;
    
    private String usGoodCW;
    
    private String usCorrectableCW;
    
    private String lastUSGoodCW;
    
    private String lastUSCorrectableCW;
    
    private String lastUSUnCorrectableCW;
    
    private String txSlotsDenied;
    
    private String lastTXSlotsDenied;
    
    public String getCmPoolingId()
    {
        return this.cmPoolingId;
    }
    
    public void setCmPoolingId(String value)
    {
        this.cmPoolingId = value;     
    }
    
    public String getFirstPoolingDate()
    {
        return this.firstPoolingDate;
    }
    
    public void setFirstPoolingDate(String value)
    {
        this.firstPoolingDate = value;     
    }
    
    public String getLastPoolingDate()
    {
        return this.lastPoolingDate;
    }
    
    public void setLastPoolingDate(String value)
    {
        this.lastPoolingDate = value;     
    }
    
    public String getRepetitions()
    {
        return this.repetitions;
    }
    
    public void setRepetitions(String value)
    {
        this.repetitions = value;     
    }
    
    public String getLastTimeoutDate()
    {
        return this.lastTimeoutDate;
    }
    
    public void setLastTimeoutDate(String value)
    {
        this.lastTimeoutDate = value;     
    }
    
    public String getTotalTimeouts()
    {
        return this.totalTimeouts;
    }
    
    public void setTotalTimeouts(String value)
    {
        this.totalTimeouts = value;     
    }
    
    public String getDsPower()
    {
        return this.dsPower;
    }
    
    public void setDsPower(String value)
    {
        this.dsPower = value;     
    }
    
    public String getUsPower()
    {
        return this.usPower;
    }
    
    public void setUsPower(String value)
    {
        this.usPower = value;     
    }
    
    public String getDsSNR()
    {
        return this.dsSNR;
    }
    
    public void setDsSNR(String value)
    {
        this.dsSNR = value;     
    }
    
    public String getUpSNR()
    {
        return this.upSNR;
    }
    
    public void setUpSNR(String value)
    {
        this.upSNR = value;     
    }
    
    public String getDownChannel()
    {
        return this.downChannel;
    }
    
    public void setDownChannel(String value)
    {
        this.downChannel = value;     
    }
    
    public String getUpChannel()
    {
        return this.upChannel;
    }
    
    public void setUpChannel(String value)
    {
        this.upChannel = value;     
    }
    
    public String getRxPower()
    {
        return this.rxPower;
    }
    
    public void setRxPower(String value)
    {
        this.rxPower = value;     
    }
    
    public String getDsGoodCW()
    {
        return this.dsGoodCW;
    }
    
    public void setDsGoodCW(String value)
    {
        this.dsGoodCW = value;     
    }
    
    public String getDsCorrectableCW()
    {
        return this.dsCorrectableCW;
    }
    
    public void setDsCorrectableCW(String value)
    {
        this.dsCorrectableCW = value;     
    }
    
    public String getLastDSGoodCW()
    {
        return this.lastDSGoodCW;
    }
    
    public void setLastDSGoodCW(String value)
    {
        this.lastDSGoodCW = value;     
    }
    
    public String getLastDSCorrectableCW()
    {
        return this.lastDSCorrectableCW;
    }
    
    public void setLastDSCorrectableCW(String value)
    {
        this.lastDSCorrectableCW = value;     
    }
    
    public String getLastDSUnCorrectableCW()
    {
        return this.lastDSUnCorrectableCW;
    }
    
    public void setLastDSUnCorrectableCW(String value)
    {
        this.lastDSUnCorrectableCW = value;     
    }
    
    public String getUsGoodCW()
    {
        return this.usGoodCW;
    }
    
    public void setUsGoodCW(String value)
    {
        this.usGoodCW = value;     
    }
    
    public String getUsCorrectableCW()
    {
        return this.usCorrectableCW;
    }
    
    public void setUsCorrectableCW(String value)
    {
        this.usCorrectableCW = value;     
    }
    
    public String getLastUSGoodCW()
    {
        return this.lastUSGoodCW;
    }
    
    public void setLastUSGoodCW(String value)
    {
        this.lastUSGoodCW = value;     
    }
    
    public String getLastUSCorrectableCW()
    {
        return this.lastUSCorrectableCW;
    }
    
    public void setLastUSCorrectableCW(String value)
    {
        this.lastUSCorrectableCW = value;     
    }
    
    public String getLastUSUnCorrectableCW()
    {
        return this.lastUSUnCorrectableCW;
    }
    
    public void setLastUSUnCorrectableCW(String value)
    {
        this.lastUSUnCorrectableCW = value;     
    }
    
    public String getTxSlotsDenied()
    {
        return this.txSlotsDenied;
    }
    
    public void setTxSlotsDenied(String value)
    {
        this.txSlotsDenied = value;     
    }
    
    public String getLastTXSlotsDenied()
    {
        return this.lastTXSlotsDenied;
    }
    
    public void setLastTXSlotsDenied(String value)
    {
        this.lastTXSlotsDenied = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("cmPoolingId"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cmPoolingId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cmPoolingId = (String)obj;
                }
                else{
                    this.cmPoolingId = "";
                }
            }
            return true;
        }
        if (info.name.equals("firstPoolingDate"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.firstPoolingDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.firstPoolingDate = (String)obj;
                }
                else{
                    this.firstPoolingDate = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastPoolingDate"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastPoolingDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastPoolingDate = (String)obj;
                }
                else{
                    this.lastPoolingDate = "";
                }
            }
            return true;
        }
        if (info.name.equals("repetitions"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.repetitions = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.repetitions = (String)obj;
                }
                else{
                    this.repetitions = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastTimeoutDate"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastTimeoutDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastTimeoutDate = (String)obj;
                }
                else{
                    this.lastTimeoutDate = "";
                }
            }
            return true;
        }
        if (info.name.equals("totalTimeouts"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.totalTimeouts = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.totalTimeouts = (String)obj;
                }
                else{
                    this.totalTimeouts = "";
                }
            }
            return true;
        }
        if (info.name.equals("dsPower"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dsPower = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.dsPower = (String)obj;
                }
                else{
                    this.dsPower = "";
                }
            }
            return true;
        }
        if (info.name.equals("usPower"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.usPower = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.usPower = (String)obj;
                }
                else{
                    this.usPower = "";
                }
            }
            return true;
        }
        if (info.name.equals("dsSNR"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dsSNR = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.dsSNR = (String)obj;
                }
                else{
                    this.dsSNR = "";
                }
            }
            return true;
        }
        if (info.name.equals("upSNR"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.upSNR = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.upSNR = (String)obj;
                }
                else{
                    this.upSNR = "";
                }
            }
            return true;
        }
        if (info.name.equals("downChannel"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.downChannel = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.downChannel = (String)obj;
                }
                else{
                    this.downChannel = "";
                }
            }
            return true;
        }
        if (info.name.equals("upChannel"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.upChannel = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.upChannel = (String)obj;
                }
                else{
                    this.upChannel = "";
                }
            }
            return true;
        }
        if (info.name.equals("rxPower"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.rxPower = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.rxPower = (String)obj;
                }
                else{
                    this.rxPower = "";
                }
            }
            return true;
        }
        if (info.name.equals("dsGoodCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dsGoodCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.dsGoodCW = (String)obj;
                }
                else{
                    this.dsGoodCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("dsCorrectableCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dsCorrectableCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.dsCorrectableCW = (String)obj;
                }
                else{
                    this.dsCorrectableCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastDSGoodCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastDSGoodCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastDSGoodCW = (String)obj;
                }
                else{
                    this.lastDSGoodCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastDSCorrectableCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastDSCorrectableCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastDSCorrectableCW = (String)obj;
                }
                else{
                    this.lastDSCorrectableCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastDSUnCorrectableCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastDSUnCorrectableCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastDSUnCorrectableCW = (String)obj;
                }
                else{
                    this.lastDSUnCorrectableCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("usGoodCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.usGoodCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.usGoodCW = (String)obj;
                }
                else{
                    this.usGoodCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("usCorrectableCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.usCorrectableCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.usCorrectableCW = (String)obj;
                }
                else{
                    this.usCorrectableCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastUSGoodCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastUSGoodCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastUSGoodCW = (String)obj;
                }
                else{
                    this.lastUSGoodCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastUSCorrectableCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastUSCorrectableCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastUSCorrectableCW = (String)obj;
                }
                else{
                    this.lastUSCorrectableCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastUSUnCorrectableCW"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastUSUnCorrectableCW = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastUSUnCorrectableCW = (String)obj;
                }
                else{
                    this.lastUSUnCorrectableCW = "";
                }
            }
            return true;
        }
        if (info.name.equals("txSlotsDenied"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.txSlotsDenied = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.txSlotsDenied = (String)obj;
                }
                else{
                    this.txSlotsDenied = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastTXSlotsDenied"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastTXSlotsDenied = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastTXSlotsDenied = (String)obj;
                }
                else{
                    this.lastTXSlotsDenied = "";
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.cmPoolingId;
        }
        else if(propertyIndex==1)
        {
            return this.firstPoolingDate;
        }
        else if(propertyIndex==2)
        {
            return this.lastPoolingDate;
        }
        else if(propertyIndex==3)
        {
            return this.repetitions;
        }
        else if(propertyIndex==4)
        {
            return this.lastTimeoutDate;
        }
        else if(propertyIndex==5)
        {
            return this.totalTimeouts;
        }
        else if(propertyIndex==6)
        {
            return this.dsPower;
        }
        else if(propertyIndex==7)
        {
            return this.usPower;
        }
        else if(propertyIndex==8)
        {
            return this.dsSNR;
        }
        else if(propertyIndex==9)
        {
            return this.upSNR;
        }
        else if(propertyIndex==10)
        {
            return this.downChannel;
        }
        else if(propertyIndex==11)
        {
            return this.upChannel;
        }
        else if(propertyIndex==12)
        {
            return this.rxPower;
        }
        else if(propertyIndex==13)
        {
            return this.dsGoodCW;
        }
        else if(propertyIndex==14)
        {
            return this.dsCorrectableCW;
        }
        else if(propertyIndex==15)
        {
            return this.lastDSGoodCW;
        }
        else if(propertyIndex==16)
        {
            return this.lastDSCorrectableCW;
        }
        else if(propertyIndex==17)
        {
            return this.lastDSUnCorrectableCW;
        }
        else if(propertyIndex==18)
        {
            return this.usGoodCW;
        }
        else if(propertyIndex==19)
        {
            return this.usCorrectableCW;
        }
        else if(propertyIndex==20)
        {
            return this.lastUSGoodCW;
        }
        else if(propertyIndex==21)
        {
            return this.lastUSCorrectableCW;
        }
        else if(propertyIndex==22)
        {
            return this.lastUSUnCorrectableCW;
        }
        else if(propertyIndex==23)
        {
            return this.txSlotsDenied;
        }
        else if(propertyIndex==24)
        {
            return this.lastTXSlotsDenied;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 25;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cmPoolingId";
            info.namespace= "";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "firstPoolingDate";
            info.namespace= "";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastPoolingDate";
            info.namespace= "";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "repetitions";
            info.namespace= "";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastTimeoutDate";
            info.namespace= "";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "totalTimeouts";
            info.namespace= "";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dsPower";
            info.namespace= "";
        }
        else if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "usPower";
            info.namespace= "";
        }
        else if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dsSNR";
            info.namespace= "";
        }
        else if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "upSNR";
            info.namespace= "";
        }
        else if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "downChannel";
            info.namespace= "";
        }
        else if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "upChannel";
            info.namespace= "";
        }
        else if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "rxPower";
            info.namespace= "";
        }
        else if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dsGoodCW";
            info.namespace= "";
        }
        else if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dsCorrectableCW";
            info.namespace= "";
        }
        else if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastDSGoodCW";
            info.namespace= "";
        }
        else if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastDSCorrectableCW";
            info.namespace= "";
        }
        else if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastDSUnCorrectableCW";
            info.namespace= "";
        }
        else if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "usGoodCW";
            info.namespace= "";
        }
        else if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "usCorrectableCW";
            info.namespace= "";
        }
        else if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastUSGoodCW";
            info.namespace= "";
        }
        else if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastUSCorrectableCW";
            info.namespace= "";
        }
        else if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastUSUnCorrectableCW";
            info.namespace= "";
        }
        else if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "txSlotsDenied";
            info.namespace= "";
        }
        else if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastTXSlotsDenied";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
