package com.iwy.wsdl.wcf;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DCQspDescriptionObj extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String ServicePackageName;
    
    private String ServicePackageCRMId;
    
    private String COS;
    
    private DCQArrayOfFlowsObj ServiceFlowsUpstream=new DCQArrayOfFlowsObj();
    
    private DCQArrayOfFlowsObj ServiceFlowsDownstream=new DCQArrayOfFlowsObj();
    
    private DCQArrayOfComandosObj GrupoComandosSNMP=new DCQArrayOfComandosObj();
    
    private DCQArrayOfOpcionesObj OpcionesAdicionales=new DCQArrayOfOpcionesObj();
    
    public String getServicePackageName()
    {
        return this.ServicePackageName;
    }
    
    public void setServicePackageName(String value)
    {
        this.ServicePackageName = value;     
    }
    
    public String getServicePackageCRMId()
    {
        return this.ServicePackageCRMId;
    }
    
    public void setServicePackageCRMId(String value)
    {
        this.ServicePackageCRMId = value;     
    }
    
    public String getCOS()
    {
        return this.COS;
    }
    
    public void setCOS(String value)
    {
        this.COS = value;     
    }
    
    public DCQArrayOfFlowsObj getServiceFlowsUpstream()
    {
        return this.ServiceFlowsUpstream;
    }
    
    public void setServiceFlowsUpstream(DCQArrayOfFlowsObj value)
    {
        this.ServiceFlowsUpstream = value;     
    }
    
    public DCQArrayOfFlowsObj getServiceFlowsDownstream()
    {
        return this.ServiceFlowsDownstream;
    }
    
    public void setServiceFlowsDownstream(DCQArrayOfFlowsObj value)
    {
        this.ServiceFlowsDownstream = value;     
    }
    
    public DCQArrayOfComandosObj getGrupoComandosSNMP()
    {
        return this.GrupoComandosSNMP;
    }
    
    public void setGrupoComandosSNMP(DCQArrayOfComandosObj value)
    {
        this.GrupoComandosSNMP = value;     
    }
    
    public DCQArrayOfOpcionesObj getOpcionesAdicionales()
    {
        return this.OpcionesAdicionales;
    }
    
    public void setOpcionesAdicionales(DCQArrayOfOpcionesObj value)
    {
        this.OpcionesAdicionales = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DCQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ServicePackageName"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ServicePackageName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ServicePackageName = (String)obj;
                }
                else{
                    this.ServicePackageName = "";
                }
            }
            return true;
        }
        if (info.name.equals("ServicePackageCRMId"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ServicePackageCRMId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ServicePackageCRMId = (String)obj;
                }
                else{
                    this.ServicePackageCRMId = "";
                }
            }
            return true;
        }
        if (info.name.equals("COS"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.COS = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.COS = (String)obj;
                }
                else{
                    this.COS = "";
                }
            }
            return true;
        }
        if (info.name.equals("ServiceFlowsUpstream"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ServiceFlowsUpstream = (DCQArrayOfFlowsObj)__envelope.get(j,DCQArrayOfFlowsObj.class,false);
            }
            return true;
        }
        if (info.name.equals("ServiceFlowsDownstream"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ServiceFlowsDownstream = (DCQArrayOfFlowsObj)__envelope.get(j,DCQArrayOfFlowsObj.class,false);
            }
            return true;
        }
        if (info.name.equals("GrupoComandosSNMP"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.GrupoComandosSNMP = (DCQArrayOfComandosObj)__envelope.get(j,DCQArrayOfComandosObj.class,false);
            }
            return true;
        }
        if (info.name.equals("OpcionesAdicionales"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.OpcionesAdicionales = (DCQArrayOfOpcionesObj)__envelope.get(j,DCQArrayOfOpcionesObj.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ServicePackageName;
        }
        else if(propertyIndex==1)
        {
            return this.ServicePackageCRMId;
        }
        else if(propertyIndex==2)
        {
            return this.COS;
        }
        else if(propertyIndex==3)
        {
            return this.ServiceFlowsUpstream;
        }
        else if(propertyIndex==4)
        {
            return this.ServiceFlowsDownstream;
        }
        else if(propertyIndex==5)
        {
            return this.GrupoComandosSNMP;
        }
        else if(propertyIndex==6)
        {
            return this.OpcionesAdicionales;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ServicePackageName";
            info.namespace= "";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ServicePackageCRMId";
            info.namespace= "";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "COS";
            info.namespace= "";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ServiceFlowsUpstream";
            info.namespace= "";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ServiceFlowsDownstream";
            info.namespace= "";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "GrupoComandosSNMP";
            info.namespace= "";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "OpcionesAdicionales";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
